apiVersion: astertower.kasterism.io/v1alpha1
kind: Astro
metadata:
  name: astro-demo
  namespace: default
spec:
  stars:
  - name: a
    type: docker
    action: GET
    image: kasterism/test_a
    port: 8000
    target: /test
    param: "{\"id\": \"S(\"init\", \"userId\")\"}"
  - name: b
    type: docker
    action: POST
    image: kasterism/test_b
    port: 8001
    target: /test 
    dependencies: [a]
    param: "{\"id\": \"S(\"init\", \"userId\")\", \"name\": \"S(\"a\", \"userName\")\"}"
  - name: c
    type: docker
    action: POST
    image: kasterism/test_c
    port: 8002
    target: /test
    dependencies: [a]
    param: "{\"name\":\"S(\"a\", \"userAgent\")\"}"
  - name: d
    type: docker
    action: POST
    image: kasterism/test_d
    port: 8003
    target: /test 
    dependencies: [b, c]
    param: "{\"level\": \"S(\"b\", \"userLevel\")\", \"kind\": \"S(\"c\", \"userKind\")\"}"
  entryparam: "{\"userId\":\"123\"}"